name: qqnotificationreply
description: QQ notification and reply based on cqhttp

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ini: ^2.0.1
  url_launcher: ^5.1.3
  shared_preferences: ^0.5.1
  path_provider: any
  permission_handler: ^8.1.1
  web_socket_channel: ^2.1.0
  event_bus: ^1.1.1
#  flutter_local_notifications: ^6.0.0
  fluttertoast: ^8.0.7
  cupertino_icons: ^1.0.0
  extended_image: ^4.0.0
  extended_text_field: ^8.0.0
  image_picker_saver: any
  share: ^2.0.4
  date_format: ^1.0.9
  image_picker: ^0.7.2+1
  image_picker_for_web: ^2.0.0
  awesome_notifications: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/cat_chat.png
    - assets/icons/default_header.png
    - assets/icons/qq.png
    - assets/icons/redbag.png
    - assets/images/loading.gif
    - assets/images/failed.png
    - assets/qq_face/0.gif
    - assets/qq_face/1.gif
    - assets/qq_face/2.gif
    - assets/qq_face/3.gif
    - assets/qq_face/4.gif
    - assets/qq_face/5.gif
    - assets/qq_face/6.gif
    - assets/qq_face/7.gif
    - assets/qq_face/8.gif
    - assets/qq_face/9.gif
    - assets/qq_face/10.gif
    - assets/qq_face/11.gif
    - assets/qq_face/12.gif
    - assets/qq_face/13.gif
    - assets/qq_face/14.gif
    - assets/qq_face/15.gif
    - assets/qq_face/16.gif
    - assets/qq_face/18.gif
    - assets/qq_face/19.gif
    - assets/qq_face/20.gif
    - assets/qq_face/21.gif
    - assets/qq_face/22.gif
    - assets/qq_face/23.gif
    - assets/qq_face/24.gif
    - assets/qq_face/25.gif
    - assets/qq_face/26.gif
    - assets/qq_face/27.gif
    - assets/qq_face/28.gif
    - assets/qq_face/29.gif
    - assets/qq_face/30.gif
    - assets/qq_face/31.gif
    - assets/qq_face/32.gif
    - assets/qq_face/33.gif
    - assets/qq_face/34.gif
    - assets/qq_face/35.gif
    - assets/qq_face/36.gif
    - assets/qq_face/37.gif
    - assets/qq_face/38.gif
    - assets/qq_face/39.gif
    - assets/qq_face/41.gif
    - assets/qq_face/42.gif
    - assets/qq_face/43.gif
    - assets/qq_face/46.gif
    - assets/qq_face/49.gif
    - assets/qq_face/53.gif
    - assets/qq_face/54.gif
    - assets/qq_face/55.gif
    - assets/qq_face/56.gif
    - assets/qq_face/57.gif
    - assets/qq_face/59.gif
    - assets/qq_face/60.gif
    - assets/qq_face/61.gif
    - assets/qq_face/62.gif
    - assets/qq_face/63.gif
    - assets/qq_face/64.gif
    - assets/qq_face/66.gif
    - assets/qq_face/67.gif
    - assets/qq_face/69.gif
    - assets/qq_face/72.gif
    - assets/qq_face/74.gif
    - assets/qq_face/75.gif
    - assets/qq_face/76.gif
    - assets/qq_face/77.gif
    - assets/qq_face/78.gif
    - assets/qq_face/79.gif
    - assets/qq_face/85.gif
    - assets/qq_face/86.gif
    - assets/qq_face/89.gif
    - assets/qq_face/90.gif
    - assets/qq_face/91.gif
    - assets/qq_face/96.gif
    - assets/qq_face/97.gif
    - assets/qq_face/98.gif
    - assets/qq_face/99.gif
    - assets/qq_face/100.gif
    - assets/qq_face/101.gif
    - assets/qq_face/102.gif
    - assets/qq_face/103.gif
    - assets/qq_face/104.gif
    - assets/qq_face/105.gif
    - assets/qq_face/106.gif
    - assets/qq_face/107.gif
    - assets/qq_face/108.gif
    - assets/qq_face/109.gif
    - assets/qq_face/110.gif
    - assets/qq_face/111.gif
    - assets/qq_face/112.gif
    - assets/qq_face/113.gif
    - assets/qq_face/114.gif
    - assets/qq_face/115.gif
    - assets/qq_face/116.gif
    - assets/qq_face/117.gif
    - assets/qq_face/118.gif
    - assets/qq_face/119.gif
    - assets/qq_face/120.gif
    - assets/qq_face/121.gif
    - assets/qq_face/122.gif
    - assets/qq_face/123.gif
    - assets/qq_face/124.gif
    - assets/qq_face/125.gif
    - assets/qq_face/126.gif
    - assets/qq_face/127.gif
    - assets/qq_face/128.gif
    - assets/qq_face/129.gif
    - assets/qq_face/130.gif
    - assets/qq_face/131.gif
    - assets/qq_face/132.gif
    - assets/qq_face/133.gif
    - assets/qq_face/134.gif
    - assets/qq_face/135.gif
    - assets/qq_face/136.gif
    - assets/qq_face/137.gif
    - assets/qq_face/138.gif
    - assets/qq_face/139.gif
    - assets/qq_face/140.gif
    - assets/qq_face/141.gif
    - assets/qq_face/142.gif
    - assets/qq_face/143.gif
    - assets/qq_face/144.gif
    - assets/qq_face/145.gif
    - assets/qq_face/146.gif
    - assets/qq_face/147.gif
    - assets/qq_face/148.gif
    - assets/qq_face/149.gif
    - assets/qq_face/150.gif
    - assets/qq_face/151.gif
    - assets/qq_face/152.gif
    - assets/qq_face/153.gif
    - assets/qq_face/154.gif
    - assets/qq_face/155.gif
    - assets/qq_face/156.gif
    - assets/qq_face/157.gif
    - assets/qq_face/158.gif
    - assets/qq_face/159.gif
    - assets/qq_face/160.gif
    - assets/qq_face/161.gif
    - assets/qq_face/162.gif
    - assets/qq_face/163.gif
    - assets/qq_face/164.gif
    - assets/qq_face/165.gif
    - assets/qq_face/166.gif
    - assets/qq_face/167.gif
    - assets/qq_face/168.gif
    - assets/qq_face/169.gif
    - assets/qq_face/170.gif
    - assets/qq_face/171.gif
    - assets/qq_face/172.gif
    - assets/qq_face/173.gif
    - assets/qq_face/174.gif
    - assets/qq_face/175.gif
    - assets/qq_face/176.gif
    - assets/qq_face/177.gif
    - assets/qq_face/178.gif
    - assets/qq_face/179.gif
    - assets/qq_face/180.gif
    - assets/qq_face/181.gif
    - assets/qq_face/182.gif
    - assets/qq_face/183.gif
    - assets/qq_face/184.gif
    - assets/qq_face/185.gif
    - assets/qq_face/186.gif
    - assets/qq_face/187.gif
    - assets/qq_face/188.gif
    - assets/qq_face/189.gif
    - assets/qq_face/190.gif
    - assets/qq_face/191.gif
    - assets/qq_face/192.gif
    - assets/qq_face/193.gif
    - assets/qq_face/194.gif
    - assets/qq_face/195.gif
    - assets/qq_face/196.gif
    - assets/qq_face/197.gif
    - assets/qq_face/198.gif
    - assets/qq_face/199.gif
    - assets/qq_face/200.gif
    - assets/qq_face/201.gif
    - assets/qq_face/202.gif
    - assets/qq_face/203.gif
    - assets/qq_face/204.gif
    - assets/qq_face/205.gif
    - assets/qq_face/206.gif
    - assets/qq_face/207.gif
    - assets/qq_face/208.gif
    - assets/qq_face/209.gif
    - assets/qq_face/210.gif
    - assets/qq_face/211.gif
    - assets/qq_face/212.gif
    - assets/qq_face/213.gif
    - assets/qq_face/214.gif
    - assets/qq_face/215.gif
    - assets/qq_face/216.gif
    - assets/qq_face/217.gif
    - assets/qq_face/218.gif
    - assets/qq_face/219.gif
    - assets/qq_face/220.gif
    - assets/qq_face/221.gif
    - assets/qq_face/222.gif
    - assets/qq_face/223.gif
    - assets/qq_face/224.gif
    - assets/qq_face/225.gif
    - assets/qq_face/226.gif
    - assets/qq_face/227.gif
    - assets/qq_face/228.gif
    - assets/qq_face/229.gif
    - assets/qq_face/230.gif
    - assets/qq_face/231.gif
    - assets/qq_face/232.gif
    - assets/qq_face/233.gif
    - assets/qq_face/234.gif
    - assets/qq_face/235.gif
    - assets/qq_face/236.gif
    - assets/qq_face/237.gif
    - assets/qq_face/238.gif
    - assets/qq_face/239.gif
    - assets/qq_face/240.gif
    - assets/qq_face/241.gif
    - assets/qq_face/242.gif
    - assets/qq_face/243.gif
    - assets/qq_face/244.gif
    - assets/qq_face/245.gif
    - assets/qq_face/246.gif
    - assets/qq_face/247.gif
    - assets/qq_face/260.gif
    - assets/qq_face/261.gif
    - assets/qq_face/262.gif
    - assets/qq_face/263.gif
    - assets/qq_face/264.gif
    - assets/qq_face/265.gif
    - assets/qq_face/266.gif
    - assets/qq_face/267.gif
    - assets/qq_face/268.gif
    - assets/qq_face/269.gif
    - assets/qq_face/270.gif
    - assets/qq_face/271.gif
    - assets/qq_face/272.gif
    - assets/qq_face/273.gif
    - assets/qq_face/274.gif
    - assets/qq_face/277.gif
    - assets/qq_face/278.gif
    - assets/qq_face/279.gif
    - assets/qq_face/280.gif
    - assets/qq_face/281.gif
    - assets/qq_face/282.gif
    - assets/qq_face/283.gif
    - assets/qq_face/284.gif
    - assets/qq_face/285.gif
    - assets/qq_face/286.gif
    - assets/qq_face/287.gif
    - assets/qq_face/288.gif
    - assets/qq_face/289.gif
    - assets/qq_face/290.gif
    - assets/qq_face/291.gif
    - assets/qq_face/292.gif
    - assets/qq_face/293.gif
    - assets/qq_face/294.gif
    - assets/qq_face/295.gif
    - assets/qq_face/296.gif
    - assets/qq_face/297.gif
    - assets/qq_face/298.gif
    - assets/qq_face/299.gif
    - assets/qq_face/300.gif
    - assets/qq_face/301.gif
    - assets/qq_face/302.gif
    - assets/qq_face/303.gif
    - assets/qq_face/304.gif
    - assets/qq_face/305.gif
    - assets/qq_face/306.gif
    - assets/qq_face/307.gif
    - assets/qq_face/308.gif
    - assets/qq_face/309.gif
    - assets/qq_face/310.gif
    - assets/qq_face/311.gif
    - assets/qq_face/312.gif
    - assets/qq_face/313.gif
    - assets/qq_face/314.gif
    - assets/qq_face/315.gif
    - assets/qq_face/316.gif
    - assets/qq_face/317.gif
    - assets/qq_face/318.gif
    - assets/qq_face/319.gif
    - assets/qq_face/320.gif
    - assets/qq_face/321.gif
    - assets/qq_face/322.gif
    - assets/qq_face/323.gif
